version: "3.9"

services:
  client:
    container_name: client
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5712:3000"
    env_file:
      - .env.local
    networks:
      - microservice-network
    restart: unless-stopped

networks:
    microservice-network:
      driver: bridge