version: "3.9"

services:
  client:
    container_name: client
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      -.:/app
    ports:
      -"3000:3000"
    env_file:
      - .env.local
    networks:
      - microservice-network

  networks:
    microservice-network:
    driver: bridge